mysql:
  host: 192.168.110.164:3306
  database: bctest
  username: root
  password: Gmz_891019_ws
  charset: utf8
  maxOpenConns: 2000
  maxIdleConns: 1000

redis:
  host: 192.168.110.164:6379
  password:
  db: 0
  maxOpenConns: 10032
  maxIdleConns: 300

canal:
  ip: 192.168.110.164
  port: 11111
  username:
  password:
  destination: example
  soTimeOut: 60000
  idleTimeOut: 3600000
  subscribe: bctest\\..*