mysql:
 host: 172.28.62.228:3306
 database: bctest
 username: root
 password: root
 charset: utf8
 maxOpenConns: 2000
 maxIdleConns: 1000

redis:
 host: 172.28.62.228:6379
 password:
 db: 0
 maxOpenConns: 10032
 maxIdleConns: 300

canal:
 ip: 172.28.62.228
 port: 11111
 username:
 password:
 destination: example
 soTimeOut: 60000
 idleTimeOut: 3600000
 schema: bctest

taskpool:
 maxThreads: 5
 timeOut: 30