hash:
 -
  tbName: b_org_info
  keys:
   - org_name
  setString: true
 -
  tbName: b_peer_info
  keys:
   - peer_fullname
  setString: true
 -
  tbName: b_user_info
  keys:
   - fab_user
   - sys_user
  setString: true
 -
  tbName: b_orderer_info
  keys:
   - ord_name
  setString: true
 -
  tbName: b_channel_info
  keys:
   - chan_name
  setString: true
 -
  tbName: b_cc_info
  keys:
   - cc_id
   - cc_name&cc_ver
  setString: true
 -
  tbName: s_peer_cc
  keys:
   - peer_fullname&cc_id
  setString: true
 -
  tbName: s_channel_cc
  keys:
   - chan_name&cc_id
  setString: true
 -
  tbName: s_channel_peer
  keys:
   - chan_name&peer_fullname
  setString: true
 - 
  tbName: l_blk_data
  keys:
   - blk_no
 - 
  tbName: l_tx_data
  keys:
   - tx_id
 - 
  tbName: l_channel_data
  keys:
   - chan_name

set:
 -
  tbName: b_peer_info
  setType: 1
  setName:
   - org_peers
  key:
   - org_name
  member:
   - peer_fullname
 -
  tbName: s_channel_peer
  setType: 4
  setName:
   - chan_peers
   - peer_chans
  key:
   - chan_name
   - peer_fullname
  member:
   - peer_fullname
   - chan_name
 -
  tbName: b_orderer_info
  setType: 3
  setName:
   - orderers
  key:
  member:
   - ord_name
 -
  tbName: b_channel_info
  setType: 3
  setName:
   - channels
  key:
  member:
   - chan_name
 -
  tbName: b_cc_info
  setType: 3
  setName:
   - ccs
  key:
  member:
   - cc_id
 -
  tbName: b_cc_info
  setType: 3
  setName:
   - ccnames
  key:
  member:
   - cc_name
 -
  tbName: b_cc_info
  setType: 1
  setName:
   - ccname_vers
  key:
   - cc_name
  member:
   - cc_ver
 -
  tbName: s_peer_cc
  setType: 4
  setName:
   - peer_ccs
   - cc_peers
  key:
   - peer_fullname
   - cc_id
  member:
   - cc_id
   - peer_fullname
 -
  tbName: s_channel_cc
  setType: 4
  setName:
   - chan_ccs
   - cc_chans
  key:
   - chan_name
   - cc_id
  member:
   - cc_id
   - chan_name
 -
  tbName: b_user_info
  setType: 1
  setName:
   - org_sysusers
  key:
   - org_name
  member:
   - sys_user
